### ISSUE TITLE
No ELF? Intended behavior?

### ISSUE THREAD

**Issue by STashakkori** [getreu/stringsext#7]
When I run stringsext on a binary, I get an empty line where the ELF designator would be. Example:

GCC: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
test.c
main
.symtab
.strtab
.shstrtab
.text
.data
.bss
.comment
.note.GNU-stack
.note.gnu.property
.rela.eh_frame

Whereas the typical strings function gives:
ELF
GCC: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
test.c
main
.symtab
.strtab
.shstrtab
.text
.data
.bss
.comment
.note.GNU-stack
.note.gnu.property
.rela.eh_frame

Is this by design? I would rather see that string in the output frankly. Thank you

**Comment by getreu** [comment]
Some years ago the output of `stringsext -e ascii` and `strings` used to bit identical, mainly for validation of the algorithm. Since, this is not a design goal any more. Nowadays some whitespace and control characters are filtered differently. The exact behaviour also depends on the `strings` version. However, `stringsext -e ascii -q 100 -- <file to be scanned>` gives you all ASCII strings with 4 bytes or longer. The string `ELF` has 3 bytes only, so you should add `-n 3`. Can you try:

    stringsext -e ascii -q 100 -n 3 -- <file to be scanned>

**Comment by STashakkori** [comment]
That command worked. But I want to see unicode and the ELF signature; to have my cake and eat it too. You my friend gave me the key.

This command got me what I needed:
stringsext -n 3 -- <file to be scanned>

I'm not sure why exactly I need to explicitly say 3 bytes or more, as it was printing blank lines without that argument. But nonetheless, thank you so much for getting me unblocked
